
# 公众号配置
# 公众号appId
"app_id": "wx435bb41065eec3b8",
# 公众号appSecret
"app_secret": "9923f2d4ad817e7147235ffe335c9c81",
# 模板消息id
"template_id": "ieCqpNoAErMZ-k2qMaOJIFmWCgjNpA1qPuMWAh2nNko",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["ieCqpNoAErMZ-k2qMaOJIFmWCgjNpA1qPuMWAh2nNko"],

# 信息配置
# 和风天气apikey
"weather_key": "c255e65caccd4363abfeefec1c0139f7",
# 天行数据apikey
"tian_api": " 6195247c2dbca966acc9ba5e6b0f6a13",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦(国外城市可能获取不到pm2.5，空气质量，今日建议等数据)
"region": "埇桥区",
# 生日1
"birthday1": {"name": "小宝", "birthday": "2004-03-01"},
# 生日2
"birthday2": {"name": "小林", "birthday": "r1997-01-01"},
# 在一起的日子，格式同上
"love_date": "2021-10-06",
# 金句中文，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}
